---
- hosts: all
  gather_facts: yes
  roles:
    - { role: basic }
    - { role: java, java_home: /opt/local, type: jre, version: 8u71, java_version: 1.8.0_71 }
    - { role: nexus ,nexus_home: /opt/local, nexus_os_user: vagrant, nexus_version: professional-2.11.1-01 , nexus_type: professional-bundle }
    - { role: nginx , nginx_os_version: 7, nginx_rpm_version: 1.10.0-1, nginx_user: vagrant, nginx_home: /opt/local, nginx_port: 443, app_name: nexus }


# ansible-playbook nexus-pro.yml --ask-vault-pass -vvv