---
- hosts: all
  gather_facts: yes
  roles:
    - { role: nginx , nginx_os_version: 7, nginx_rpm_version: 1.10.0-1, nginx_user: vagrant, nginx_home: /opt/local, nginx_port: 443 }

# ansible-playbook nginx.yml

