---
# This playbook installs java jre & jdk as a non root user.

- hosts: all
  gather_facts: yes
  roles:
    - { role: java, java_home: /opt/local, type: jre, version: 8u71, java_version: 1.8.0_71 }