---

- name: create home directory
  become: yes
  file:
    path: "{{ base_dir }}"
    state: directory
    mode: 0750

- name: get the username running the deploy
  command: whoami
  register: username

- name: changing permissions for local directory
  become: yes
  file:
    path: "{{ base_dir }}"
    owner: "{{ username.stdout }}"
    group: "{{ username.stdout }}"
    mode: 0755



#ansible-playbook test.yml -i "nexus.dev", -k -u vagrant --ask-vault-pass  -vvvv
