---
- name: create a directory for java
  file:
    path: "{{ java_home }}/java"
    state: directory

- name: download java
  get_url:
    url: "{{ java_artifactory_url }}"
    dest: "/tmp/{{ downloaded_java_type }}"

- name: extract java
  unarchive:
    src: "/tmp/{{ downloaded_java_type }}"
    dest: "{{ java_home }}/java"
    copy: no

- name: symlinking Java directory to default
  file:
    src: "{{ java_home }}/java/jre{{ java_version }}"
    dest: "{{ java_home }}/java/default"
    state: link
  when: type == 'jre'


# Convert to blockinfile
- name: set JAVA_HOME in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export JAVA_HOME={{ java_home }}/java/default/bin/"
    create: yes
    state: present
    mode: 0555
  when: type == 'jre'

- name: export PATH in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=$PATH:$JAVA_HOME"
    create: yes
    state: present
    mode: 0555
  when: type == 'jre'
